[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.1"
futures = "0.3.28"
chrono = "0.4.26"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]
